### PR TITLE
Add tether offload libraries for VNDK 26 arm64

### PR DESCRIPTION
**Pull request by notsyncing**
This fixes the `ipacm` crashing due to missing libraries on my mix2s.

### CODE REVIEW

**Comment by phhusson** [comment]
Where did you get those libs from?

**Comment by notsyncing** [comment]
From the stock MIUI firmware, miui_MIMIX2S_8.7.26_aeeb25f521_8.0

**Comment by phhusson** [comment]
Please try with https://github.com/phhusson/vendor_vndk/commit/2afe45f3eee72aa7ec78072c890962d3af54c7cb
Those were built from an AOSP 8.0, by coping tetheroffload folder from AOSP 8.1, deleting vts, and removing vndk mention in Android.bp

**Comment by notsyncing** [comment]
Confirmed they are working. I'm closing this. Thanks very much!

**Pull request closed without merging**
