### PR TITLE
vndk-29: Include libcamera_client.so

### PR DESCRIPTION
**Pull request by SamarV-121**
* Fixes camera on Samsung galaxy M20, M30

### CODE REVIEW

**Comment by phhusson** [comment]
Is it tested? Where does it come from?

**Comment by SamarV-121** [comment]
Yep, tested

From stock ROM of m20

**Comment by phhusson** [comment]
Please use the files from aosp gsi instead.

**Comment by SamarV-121** [comment]
Working with aosp blobs too

**Comment by SamarV-121** [comment]
Should I just add this to rw-system.sh
    cp /system/lib/libcamera_client.so /system/lib/vndk-29/libcamera_client.so ? Under m20 guard obv

**Comment by phhusson** [comment]
No, commit /system/lib/libcamera_client.so in vndk-29

Le mar. 30 juin 2020 à 11:14, ѕαмαя νιѕρυтє <notifications@github.com> a
écrit :

**Comment by SamarV-121** [comment]
K

**Pull request closed without merging**
